### ISSUE TITLE
Deriving subterm with non-uniform parameters

### ISSUE THREAD

**Issue by kyoDralliam** [mattam82/Coq-Equations#246]
Equations (version 1.2 on Coq 8.10.0) has troubles with non-uniform parameters of inductive types.

Minimal (contrived) example:
```coq
From Equations Require Import Equations.

Inductive t (u:unit) :=
| strange : t tt  -> t u.

Derive Subterm for t.
```
Produces
```
Error: Illegal application: 
The term "t_direct_subterm" of type "forall u : unit, test.t u -> test.t u -> Prop" cannot be applied to the terms
 "u" : "unit"
 "t" : "test.t tt"
 "strange u t" : "test.t u"
The 2nd term has type "test.t tt" which should be coercible to "test.t u".
```
Changing the parameter to an index leaves a proof obligation `forall a, Acc t_subterm a` (that can be discharged).

**Comment by mattam82** [comment]
There are two combined problems: subterm did not handle non-uniform parameters (this is fixed by #287) and also, your contrived example was falling in Prop so no well-founded subterm relation could be proven on it (that would contradict proof irrelevance, so if you really discharged it completely I'm curious how :). The problem with these inductives that fall in Prop implicitely is that Coq generates only a non-dependent eliminator for them whereas the subterm automation expects a dependent schema to be available. Anyway that's a case where subterm cannot really apply.  If we put `t (u : unit) : Set` everything works out fine now.

**Comment by kyoDralliam** [comment]
@mattam82 The thing about Prop was an unexpected side-effect of the simplification and the "real" case landed in Type. In my local tests, now it successfully derives the subterm relation but it doesn't seem to be able to prove automatically the well-foundedness obligation.
Can you reproduce that or is it specific to my setup ?
Also solving the obligation by hand (see below), it looks rather uniform...

```coq
From Equations Require Import Equations.

Section ImpMonad.
  Context (S:Type).

  Inductive Imp (A:Type) : Type :=
  | ImpRet : A -> Imp A
  | ImpGet : (S -> Imp A) -> Imp A
  | ImpSet : S -> Imp A -> Imp A
  | ImpDoWhile : Imp bool -> Imp A -> Imp A.
End ImpMonad.

Derive Subterm for Imp.
Next Obligation.
  apply Transitive_Closure.Acc_clos_trans.
  depelim a.
  induction pr2; constructor; intros ? h ; depelim h; try discriminate.
  - depelim y; cbn in *. injection H1; intros <-. rewrite H0. apply H.
  - depelim y; cbn in *. injection H; intros <- <-. apply IHpr2.
  - depelim y; cbn in *. injection H; intros <- <-. apply IHpr2_2.
  - depelim y; cbn in *. depelim H. injection H; intros <- <-. apply IHpr2_1.
Qed.
```

**Comment by mattam82** [comment]
Oh right, you also need to derive NoConfusion/NoConfusionHom before Subterm. I'll add a check for that.
