### ISSUE TITLE
 git grep Obj.magic | grep -o Obj.magic | wc -l should give 0

### ISSUE THREAD

**Issue by maximedenes** [mattam82/Coq-Equations#40]
Currently it gives 87 on the 8.8+alpha branch!

**Comment by cmangin** [comment]
For the record, all of them are trivially removable. I think they were due to deficiencies in the API (which is gone for now, hence why it's trivial to remove all of them).
Proof with this [commit](https://github.com/cmangin/Coq-Equations/commit/166fe43706c4ce011fb3ebacb9bb3918beba0118).

Do you want me to merge this @mattam82 or do we have reason to believe the API will come back?

**Comment by mattam82** [comment]
Sure you can merge this, it was due to the API indeed.
Le mer. 10 janv. 2018 à 07:28, Cyprien Mangin <notifications@github.com> a
écrit :

**Comment by cmangin** [comment]
No more `Obj.magic` for now, thanks for the report.
